import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { en_US, provideNzI18n } from 'ng-zorro-antd/i18n';
import { registerLocaleData } from '@angular/common';
import en from '@angular/common/locales/en';
import { provideNzDateFnsAdapter } from 'ng-zorro-antd/core/time';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  DownloadOutline,
  FileOutline,
  AppstoreOutline,
  ClockCircleOutline,
  CopyOutline,
  CrownOutline,
  FlagOutline,
  LockOutline,
  AudioMutedOutline,
  AudioOutline,
  DesktopOutline,
  MessageOutline,
  PhoneOutline,
  SendOutline,
  TeamOutline,
  PlayCircleOutline,
  ReloadOutline,
  WarningOutline,
  ArrowLeftOutline,
  GlobalOutline,
  QuestionCircleOutline,
  DashboardOutline,
  CalendarOutline,
  CheckSquareOutline,
  HighlightOutline,
  FileTextOutline,
  ContactsOutline,
  SettingOutline,
  BellOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  VideoCameraOutline,
  UserOutline,
  LogoutOutline,
  PlusOutline,
  SearchOutline,
  DownOutline,
  MoreOutline,
  EditOutline,
  DeleteOutline,
  EyeOutline,
  EyeInvisibleOutline,
  CloseOutline,
  CheckOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  ApartmentOutline,
  UserAddOutline,
  ExpandOutline,
  ShrinkOutline,
  RightOutline,
  UnlockOutline,
  KeyOutline,
} from '@ant-design/icons-angular/icons';

registerLocaleData(en);

const icons = [
  DownloadOutline,
  FileOutline,
  AppstoreOutline,
  ClockCircleOutline,
  CopyOutline,
  CrownOutline,
  FlagOutline,
  LockOutline,
  AudioMutedOutline,
  AudioOutline,
  DesktopOutline,
  MessageOutline,
  PhoneOutline,
  SendOutline,
  TeamOutline,
  PlayCircleOutline,
  ReloadOutline,
  WarningOutline,
  ArrowLeftOutline,
  GlobalOutline,
  QuestionCircleOutline,
  DashboardOutline,
  CalendarOutline,
  CheckSquareOutline,
  HighlightOutline,
  FileTextOutline,
  ContactsOutline,
  SettingOutline,
  BellOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  VideoCameraOutline,
  UserOutline,
  LogoutOutline,
  PlusOutline,
  SearchOutline,
  DownOutline,
  MoreOutline,
  EditOutline,
  DeleteOutline,
  EyeOutline,
  EyeInvisibleOutline,
  CloseOutline,
  CheckOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  ApartmentOutline,
  UserAddOutline,
  ExpandOutline,
  ShrinkOutline,
  RightOutline,
  UnlockOutline,
  KeyOutline,
];

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideAnimationsAsync(),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideNzI18n(en_US),
    provideNzDateFnsAdapter(),
    provideNzIcons(icons),
  ],
};
