import type {
  Participant,
  Meeting,
  ChatMessage,
  TranscriptSegment,
  Task,
  MeetingMinutes,
  Notification,
  MeetingDocument,
} from '@/types';

export const currentUser: Participant = {
  id: 'u1',
  name: 'Nguyen Van An',
  email: 'an.nguyenvan@company.com',
  avatarColor: 'bg-primary-600',
  role: 'host',
  department: 'IT Department',
  isMuted: false,
  isCameraOn: true,
  isHandRaised: false,
  isScreenSharing: false,
  isSpeaking: false,
  hasLeft: false,
  joinedAt: '09:00',
};

export const participants: Participant[] = [
  {
    id: 'u1',
    name: 'Nguyen Van An',
    email: 'an.nguyenvan@company.com',
    avatarColor: 'bg-primary-600',
    role: 'host',
    department: 'IT Department',
    isMuted: false,
    isCameraOn: true,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: true,
    hasLeft: false,
    joinedAt: '09:00',
  },
  {
    id: 'u2',
    name: 'Tran Thi Bich',
    email: 'bich.tranthi@company.com',
    avatarColor: 'bg-accent-600',
    role: 'secretary',
    department: 'HR Department',
    isMuted: true,
    isCameraOn: false,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:01',
  },
  {
    id: 'u3',
    name: 'Le Minh Cuong',
    email: 'cuong.leminh@company.com',
    avatarColor: 'bg-success-600',
    role: 'member',
    department: 'Finance',
    isMuted: false,
    isCameraOn: true,
    isHandRaised: true,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:02',
  },
  {
    id: 'u4',
    name: 'Pham Thi Dung',
    email: 'dung.phamthi@company.com',
    avatarColor: 'bg-warning-600',
    role: 'member',
    department: 'Marketing',
    isMuted: true,
    isCameraOn: true,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:02',
  },
  {
    id: 'u5',
    name: 'Hoang Van Em',
    email: 'em.hoangvan@company.com',
    avatarColor: 'bg-error-600',
    role: 'member',
    department: 'Engineering',
    isMuted: false,
    isCameraOn: false,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:03',
  },
  {
    id: 'u6',
    name: 'Vu Thi Phuong',
    email: 'phuong.vuthi@company.com',
    avatarColor: 'bg-primary-500',
    role: 'guest',
    department: 'External Partner',
    isMuted: true,
    isCameraOn: false,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:05',
  },
];

export const lobbyParticipants: Participant[] = [
  {
    id: 'g1',
    name: 'Guest - Khach moi 1',
    email: 'guest1@external.com',
    avatarColor: 'bg-ink-400',
    role: 'guest',
    department: 'External',
    isMuted: false,
    isCameraOn: true,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:06',
  },
  {
    id: 'g2',
    name: 'Guest - Khach moi 2',
    email: 'guest2@external.com',
    avatarColor: 'bg-ink-500',
    role: 'guest',
    department: 'External',
    isMuted: false,
    isCameraOn: false,
    isHandRaised: false,
    isScreenSharing: false,
    isSpeaking: false,
    hasLeft: false,
    joinedAt: '09:07',
  },
];

export const meetings: Meeting[] = [
  {
    id: 'm1',
    title: 'Q3 Financial Review Meeting',
    description: 'Review Q3 financial performance and discuss Q4 budget allocation',
    date: '2026-08-25',
    startTime: '09:00',
    endTime: '10:30',
    room: 'Conference Room A',
    status: 'live',
    hostId: 'u1',
    hostName: 'Nguyen Van An',
    participantIds: ['u1', 'u2', 'u3', 'u4', 'u5', 'u6'],
    agenda: [
      { id: 'a1', title: 'Opening & Attendance', duration: 5, presenter: 'Nguyen Van An', completed: true },
      { id: 'a2', title: 'Q3 Revenue Report', duration: 20, presenter: 'Le Minh Cuong', completed: true },
      { id: 'a3', title: 'Budget Variance Analysis', duration: 15, presenter: 'Le Minh Cuong', completed: false },
      { id: 'a4', title: 'Q4 Budget Proposal', duration: 25, presenter: 'Nguyen Van An', completed: false },
      { id: 'a5', title: 'Action Items & Closing', duration: 10, presenter: 'Tran Thi Bich', completed: false },
    ],
    isSecure: true,
    hasPassword: true,
    recordingEnabled: true,
    aiEnabled: true,
  },
  {
    id: 'm2',
    title: 'Product Launch Strategy',
    description: 'Finalize go-to-market strategy for new product line',
    date: '2026-08-26',
    startTime: '14:00',
    endTime: '15:30',
    room: 'Conference Room B',
    status: 'scheduled',
    hostId: 'u1',
    hostName: 'Nguyen Van An',
    participantIds: ['u1', 'u3', 'u4', 'u5'],
    agenda: [
      { id: 'a1', title: 'Market Analysis Overview', duration: 20, presenter: 'Pham Thi Dung', completed: false },
      { id: 'a2', title: 'Pricing Strategy', duration: 30, presenter: 'Le Minh Cuong', completed: false },
      { id: 'a3', title: 'Launch Timeline', duration: 25, presenter: 'Hoang Van Em', completed: false },
    ],
    isSecure: false,
    hasPassword: false,
    recordingEnabled: true,
    aiEnabled: true,
  },
  {
    id: 'm3',
    title: 'Weekly Engineering Sync',
    description: 'Weekly progress sync for engineering team',
    date: '2026-08-27',
    startTime: '10:00',
    endTime: '10:45',
    room: 'Conference Room A',
    status: 'scheduled',
    hostId: 'u5',
    hostName: 'Hoang Van Em',
    participantIds: ['u1', 'u5'],
    agenda: [
      { id: 'a1', title: 'Sprint Review', duration: 20, presenter: 'Hoang Van Em', completed: false },
      { id: 'a2', title: 'Blockers & Risks', duration: 15, presenter: 'Nguyen Van An', completed: false },
    ],
    isSecure: false,
    hasPassword: false,
    recordingEnabled: false,
    aiEnabled: true,
  },
  {
    id: 'm4',
    title: 'Client Onboarding — Acme Corp',
    description: 'Onboarding session for new enterprise client',
    date: '2026-08-22',
    startTime: '13:00',
    endTime: '14:00',
    room: 'Conference Room C',
    status: 'completed',
    hostId: 'u1',
    hostName: 'Nguyen Van An',
    participantIds: ['u1', 'u2', 'u6'],
    agenda: [
      { id: 'a1', title: 'Company Overview', duration: 15, presenter: 'Nguyen Van An', completed: true },
      { id: 'a2', title: 'Platform Walkthrough', duration: 30, presenter: 'Tran Thi Bich', completed: true },
      { id: 'a3', title: 'Next Steps', duration: 15, presenter: 'Nguyen Van An', completed: true },
    ],
    isSecure: true,
    hasPassword: true,
    recordingEnabled: true,
    aiEnabled: true,
  },
  {
    id: 'm5',
    title: 'HR Policy Update Briefing',
    description: 'Briefing on updated HR policies for all departments',
    date: '2026-08-20',
    startTime: '11:00',
    endTime: '12:00',
    room: 'Conference Room B',
    status: 'completed',
    hostId: 'u2',
    hostName: 'Tran Thi Bich',
    participantIds: ['u1', 'u2', 'u3', 'u4'],
    agenda: [
      { id: 'a1', title: 'Policy Changes Overview', duration: 25, presenter: 'Tran Thi Bich', completed: true },
      { id: 'a2', title: 'Q&A Session', duration: 25, presenter: 'All', completed: true },
    ],
    isSecure: false,
    hasPassword: false,
    recordingEnabled: false,
    aiEnabled: false,
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'c1',
    senderId: 'u2',
    senderName: 'Tran Thi Bich',
    senderAvatarColor: 'bg-accent-600',
    content: 'Good morning everyone, the agenda is shared in the workspace.',
    timestamp: '09:01',
    isDirect: false,
  },
  {
    id: 'c2',
    senderId: 'u3',
    senderName: 'Le Minh Cuong',
    senderAvatarColor: 'bg-success-600',
    content: 'I have the Q3 revenue slides ready, sharing now.',
    timestamp: '09:03',
    isDirect: false,
  },
  {
    id: 'c3',
    senderId: 'u1',
    senderName: 'Nguyen Van An',
    senderAvatarColor: 'bg-primary-600',
    content: 'Great, let\'s start with the attendance check.',
    timestamp: '09:05',
    isDirect: false,
  },
  {
    id: 'c4',
    senderId: 'u4',
    senderName: 'Pham Thi Dung',
    senderAvatarColor: 'bg-warning-600',
    content: 'I\'ll be presenting the marketing budget impact after Cuong.',
    timestamp: '09:08',
    isDirect: false,
  },
  {
    id: 'c5',
    senderId: 'u1',
    senderName: 'Nguyen Van An',
    senderAvatarColor: 'bg-primary-600',
    content: 'Can you share the variance analysis doc with me privately?',
    timestamp: '09:10',
    isDirect: true,
    recipientName: 'Le Minh Cuong',
  },
];

export const transcriptSegments: TranscriptSegment[] = [
  {
    id: 't1',
    speakerId: 'u1',
    speakerName: 'Nguyen Van An',
    text: 'Welcome everyone to the Q3 Financial Review. Let\'s start by confirming attendance.',
    startTime: '00:00',
    endTime: '00:08',
    isDraft: false,
    language: 'en',
  },
  {
    id: 't2',
    speakerId: 'u2',
    speakerName: 'Tran Thi Bich',
    text: 'All participants confirmed. We have six attendees including one external partner.',
    startTime: '00:09',
    endTime: '00:15',
    isDraft: false,
    language: 'en',
  },
  {
    id: 't3',
    speakerId: 'u3',
    speakerName: 'Le Minh Cuong',
    text: 'Q3 revenue came in at 18.5 billion VND, which is 12% above target. The growth was primarily driven by the enterprise segment.',
    startTime: '00:16',
    endTime: '00:28',
    isDraft: false,
    language: 'en',
  },
  {
    id: 't4',
    speakerId: 'u1',
    speakerName: 'Nguyen Van An',
    text: 'Excellent results. Let\'s move on to the budget variance analysis. Cuong, can you walk us through the major variances?',
    startTime: '00:29',
    endTime: '00:38',
    isDraft: true,
    language: 'en',
  },
  {
    id: 't5',
    speakerId: 'u3',
    speakerName: 'Le Minh Cuong',
    text: 'The main variance was in marketing spend, which was 8% under budget. IT infrastructure was 5% over due to the cloud migration project.',
    startTime: '00:39',
    endTime: '00:52',
    isDraft: true,
    language: 'en',
  },
];

export const tasks: Task[] = [
  {
    id: 'task1',
    title: 'Prepare Q4 budget proposal draft',
    description: 'Create detailed Q4 budget proposal based on Q3 variance analysis and department requests.',
    assigneeId: 'u3',
    assigneeName: 'Le Minh Cuong',
    assigneeDepartment: 'Finance',
    deadline: '2026-08-28',
    status: 'pending',
    priority: 'high',
    meetingId: 'm1',
    meetingTitle: 'Q3 Financial Review Meeting',
  },
  {
    id: 'task2',
    title: 'Update marketing campaign timeline',
    description: 'Revise the Q4 marketing campaign timeline to align with new budget allocation.',
    assigneeId: 'u4',
    assigneeName: 'Pham Thi Dung',
    assigneeDepartment: 'Marketing',
    deadline: '2026-08-30',
    status: 'in-progress',
    priority: 'medium',
    meetingId: 'm1',
    meetingTitle: 'Q3 Financial Review Meeting',
  },
  {
    id: 'task3',
    title: 'Schedule cloud migration review',
    description: 'Set up a technical review meeting for the cloud migration project overspend.',
    assigneeId: 'u5',
    assigneeName: 'Hoang Van Em',
    assigneeDepartment: 'Engineering',
    deadline: '2026-08-27',
    status: 'pending',
    priority: 'high',
    meetingId: 'm1',
    meetingTitle: 'Q3 Financial Review Meeting',
  },
  {
    id: 'task4',
    title: 'Finalize client onboarding documentation',
    description: 'Complete and distribute the Acme Corp onboarding packet.',
    assigneeId: 'u2',
    assigneeName: 'Tran Thi Bich',
    assigneeDepartment: 'HR',
    deadline: '2026-08-24',
    status: 'overdue',
    priority: 'medium',
    meetingId: 'm4',
    meetingTitle: 'Client Onboarding — Acme Corp',
  },
  {
    id: 'task5',
    title: 'Distribute updated HR policies',
    description: 'Send updated HR policy documents to all department heads.',
    assigneeId: 'u2',
    assigneeName: 'Tran Thi Bich',
    assigneeDepartment: 'HR',
    deadline: '2026-08-23',
    status: 'completed',
    priority: 'low',
    meetingId: 'm5',
    meetingTitle: 'HR Policy Update Briefing',
  },
];

export const meetingMinutes: MeetingMinutes[] = [
  {
    id: 'mom1',
    meetingId: 'm4',
    meetingTitle: 'Client Onboarding — Acme Corp',
    date: '2026-08-22',
    summary:
      'The meeting covered the company overview and platform walkthrough for Acme Corp. The client was satisfied with the platform capabilities and agreed to proceed with the onboarding process. Next steps include finalizing the contract and scheduling the technical setup session.',
    keyDecisions: [
      'Acme Corp confirmed for enterprise tier onboarding',
      'Technical setup session to be scheduled within 2 weeks',
      'Dedicated account manager assigned to Acme Corp',
    ],
    actionItems: [
      'Finalize and sign enterprise contract',
      'Schedule technical setup session',
      'Prepare onboarding documentation packet',
    ],
    attendees: ['Nguyen Van An', 'Tran Thi Bich', 'Vu Thi Phuong'],
    status: 'approved',
    generatedAt: '2026-08-22 14:05',
    approvedBy: 'Tran Thi Bich',
  },
  {
    id: 'mom2',
    meetingId: 'm5',
    meetingTitle: 'HR Policy Update Briefing',
    date: '2026-08-20',
    summary:
      'The HR department presented updates to internal policies covering remote work, leave entitlements, and performance review processes. All department heads acknowledged the changes and agreed to cascade the information to their teams.',
    keyDecisions: [
      'Remote work policy updated to 3 days/week hybrid model',
      'Performance reviews moved to quarterly cadence',
      'New leave request system goes live September 1st',
    ],
    actionItems: [
      'Distribute updated policy documents to all teams',
      'Configure new leave request system',
      'Schedule team-level briefing sessions',
    ],
    attendees: ['Nguyen Van An', 'Tran Thi Bich', 'Le Minh Cuong', 'Pham Thi Dung'],
    status: 'approved',
    generatedAt: '2026-08-20 12:10',
    approvedBy: 'Tran Thi Bich',
  },
];

export const notifications: Notification[] = [
  {
    id: 'n1',
    type: 'warning',
    title: 'Task Overdue',
    message: 'Finalize client onboarding documentation is 1 day overdue.',
    timestamp: '2h ago',
    read: false,
  },
  {
    id: 'n2',
    type: 'info',
    title: 'Meeting Reminder',
    message: 'Q3 Financial Review Meeting starts in 15 minutes.',
    timestamp: '15m ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'success',
    title: 'Minutes Approved',
    message: 'HR Policy Update Briefing minutes have been approved.',
    timestamp: '3d ago',
    read: true,
  },
  {
    id: 'n4',
    type: 'info',
    title: 'New Task Assigned',
    message: 'You have been assigned to prepare Q4 budget proposal draft.',
    timestamp: '1d ago',
    read: true,
  },
];

export const weeklyMeetingData = [
  { day: 'Mon', count: 2 },
  { day: 'Tue', count: 3 },
  { day: 'Wed', count: 1 },
  { day: 'Thu', count: 4 },
  { day: 'Fri', count: 2 },
  { day: 'Sat', count: 0 },
  { day: 'Sun', count: 0 },
];

export const meetingDocuments: MeetingDocument[] = [
  {
    id: 'doc1',
    meetingId: 'm1',
    name: 'Q3-Financial-Report.pdf',
    type: 'pdf',
    size: '2.4 MB',
    uploadedBy: 'Le Minh Cuong',
    uploadedAt: '2026-08-25 08:45',
  },
  {
    id: 'doc2',
    meetingId: 'm1',
    name: 'Budget-Variance-Analysis.xlsx',
    type: 'xlsx',
    size: '1.1 MB',
    uploadedBy: 'Le Minh Cuong',
    uploadedAt: '2026-08-25 08:50',
  },
  {
    id: 'doc3',
    meetingId: 'm1',
    name: 'Q4-Budget-Proposal-Draft.docx',
    type: 'docx',
    size: '340 KB',
    uploadedBy: 'Nguyen Van An',
    uploadedAt: '2026-08-25 08:30',
  },
  {
    id: 'doc4',
    meetingId: 'm1',
    name: 'Marketing-Spend-Summary.pptx',
    type: 'pptx',
    size: '5.2 MB',
    uploadedBy: 'Pham Thi Dung',
    uploadedAt: '2026-08-25 08:55',
  },
  {
    id: 'doc5',
    meetingId: 'm2',
    name: 'Go-To-Market-Strategy.pdf',
    type: 'pdf',
    size: '3.1 MB',
    uploadedBy: 'Pham Thi Dung',
    uploadedAt: '2026-08-24 16:00',
  },
  {
    id: 'doc6',
    meetingId: 'm4',
    name: 'Acme-Corp-Onboarding-Guide.pdf',
    type: 'pdf',
    size: '1.8 MB',
    uploadedBy: 'Tran Thi Bich',
    uploadedAt: '2026-08-22 12:00',
  },
];

export const orgContacts = [
  { id: 'u2', name: 'Tran Thi Bich', department: 'HR Department', avatarColor: 'bg-accent-600', email: 'bich.tranthi@company.com' },
  { id: 'u3', name: 'Le Minh Cuong', department: 'Finance', avatarColor: 'bg-success-600', email: 'cuong.leminh@company.com' },
  { id: 'u4', name: 'Pham Thi Dung', department: 'Marketing', avatarColor: 'bg-warning-600', email: 'dung.phamthi@company.com' },
  { id: 'u5', name: 'Hoang Van Em', department: 'Engineering', avatarColor: 'bg-error-600', email: 'em.hoangvan@company.com' },
  { id: 'u6', name: 'Vu Thi Phuong', department: 'External Partner', avatarColor: 'bg-primary-500', email: 'phuong.vuthi@company.com' },
  { id: 'u7', name: 'Dang Quoc Gia', department: 'IT Department', avatarColor: 'bg-primary-700', email: 'gia.dangquoc@company.com' },
  { id: 'u8', name: 'Bui Thi Hoa', department: 'Sales', avatarColor: 'bg-accent-700', email: 'hoa.buithi@company.com' },
];
